import images from "./images";
import { propertiesImages } from "@/lib/data";

// Fallback if propertiesImages is not available
const getPropertyImage = (index: number): any => {
  if (propertiesImages && propertiesImages[index]) {
    return propertiesImages[index];
  }
  // Alternate between images
  return index % 2 === 0 ? images.newYork : images.japan;
};

export type DummyProperty = {
  $id: string;
  image: string;
  name: string;
  address: string;
  price: number;
  rating: number;
  type: string;
  description?: string;
  bedrooms?: number;
  bathrooms?: number;
  area?: number;
  facilities?: string[];
};

// Generate dummy properties
export const dummyProperties: DummyProperty[] = [
  {
    $id: "prop-1",
    name: "Luxury Downtown Apartment",
    address: "123 Main Street, Downtown District",
    price: 2500,
    rating: 4.8,
    type: "Apartments",
    image: images.newYork,
    description:
      "Beautiful modern apartment in the heart of downtown with stunning city views.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking"],
  },
  {
    $id: "prop-2",
    name: "Cozy Studio Loft",
    address: "456 Arts District, Creative Quarter",
    price: 1200,
    rating: 4.5,
    type: "Studios",
    image: images.japan,
    description: "Charming studio loft perfect for young professionals.",
    bedrooms: 0,
    bathrooms: 1,
    area: 600,
    facilities: ["Wifi", "Laundry"],
  },
  {
    $id: "prop-3",
    name: "Spacious Family House",
    address: "789 Oak Avenue, Suburban Heights",
    price: 4500,
    rating: 4.9,
    type: "House",
    image: images.newYork,
    description: "Perfect family home with large yard and modern amenities.",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking", "Pet Center"],
  },
  {
    $id: "prop-4",
    name: "Modern Condo Suite",
    address: "321 River Road, Waterfront",
    price: 3200,
    rating: 4.7,
    type: "Condos",
    image: images.japan,
    description: "Elegant condo with river views and premium finishes.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking"],
  },
  {
    $id: "prop-5",
    name: "Chic Duplex Penthouse",
    address: "555 Skyline Boulevard, Heights District",
    price: 5500,
    rating: 5.0,
    type: "Duplexes",
    image: images.newYork,
    description: "Stunning penthouse duplex with panoramic city views.",
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking", "Cutlery"],
  },
  {
    $id: "prop-6",
    name: "Elegant Villa Estate",
    address: "777 Estate Lane, Luxury Hills",
    price: 8500,
    rating: 4.9,
    type: "Villa",
    image: images.japan,
    description: "Luxurious villa estate with private pool and gardens.",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    facilities: [
      "Wifi",
      "Gym",
      "Swimming pool",
      "Car Parking",
      "Pet Center",
      "Cutlery",
    ],
  },
  {
    $id: "prop-7",
    name: "Urban Townhome",
    address: "999 Urban Street, City Center",
    price: 3800,
    rating: 4.6,
    type: "Townhomes",
    image: images.newYork,
    description: "Contemporary townhome in vibrant city center.",
    bedrooms: 3,
    bathrooms: 2.5,
    area: 2000,
    facilities: ["Wifi", "Car Parking", "Laundry"],
  },
  {
    $id: "prop-8",
    name: "Budget-Friendly Studio",
    address: "111 Budget Avenue, Affordable District",
    price: 800,
    rating: 3.8,
    type: "Studios",
    image: images.japan,
    description:
      "Affordable studio apartment for students and young professionals.",
    bedrooms: 0,
    bathrooms: 1,
    area: 400,
    facilities: ["Wifi"],
  },
  {
    $id: "prop-9",
    name: "Premium Apartment Complex",
    address: "222 Premium Plaza, Elite Quarter",
    price: 4200,
    rating: 4.8,
    type: "Apartments",
    image: images.newYork,
    description:
      "Premium apartment with concierge service and luxury amenities.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking", "Laundry"],
  },
  {
    $id: "prop-10",
    name: "Beachfront Condo",
    address: "333 Ocean Drive, Beach District",
    price: 5000,
    rating: 4.9,
    type: "Condos",
    image: images.japan,
    description:
      "Stunning beachfront condo with ocean views and direct beach access.",
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking"],
  },
  {
    $id: "prop-11",
    name: "Historic Townhome",
    address: "444 Heritage Lane, Historic District",
    price: 2800,
    rating: 4.4,
    type: "Townhomes",
    image: images.newYork,
    description:
      "Charming historic townhome with original architectural details.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    facilities: ["Wifi", "Car Parking"],
  },
  {
    $id: "prop-12",
    name: "Modern Minimalist Studio",
    address: "555 Minimalist Way, Design District",
    price: 1500,
    rating: 4.6,
    type: "Studios",
    image: images.japan,
    description: "Sleek minimalist studio with high-end finishes.",
    bedrooms: 0,
    bathrooms: 1,
    area: 700,
    facilities: ["Wifi", "Laundry"],
  },
  {
    $id: "prop-13",
    name: "Family-Friendly House",
    address: "666 Family Circle, Suburban Park",
    price: 3800,
    rating: 4.7,
    type: "House",
    image: images.newYork,
    description: "Spacious family home near parks and schools.",
    bedrooms: 4,
    bathrooms: 2.5,
    area: 2400,
    facilities: ["Wifi", "Car Parking", "Pet Center"],
  },
  {
    $id: "prop-14",
    name: "Luxury Penthouse Apartment",
    address: "777 Tower Heights, Sky District",
    price: 6500,
    rating: 5.0,
    type: "Apartments",
    image: images.japan,
    description: "Ultra-luxury penthouse with private terrace and city views.",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    facilities: ["Wifi", "Gym", "Swimming pool", "Car Parking", "Cutlery"],
  },
  {
    $id: "prop-15",
    name: "Cozy Cottage House",
    address: "888 Cottage Lane, Quiet Suburbs",
    price: 2200,
    rating: 4.3,
    type: "House",
    image: images.newYork,
    description: "Charming cottage with garden and peaceful surroundings.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    facilities: ["Wifi", "Car Parking", "Pet Center"],
  },
  {
    $id: "prop-16",
    name: "Executive Condo Suite",
    address: "999 Business Boulevard, Corporate District",
    price: 4800,
    rating: 4.8,
    type: "Condos",
    image: getPropertyImage(0),
    description: "Executive suite perfect for business professionals.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1900,
    facilities: ["Wifi", "Gym", "Car Parking", "Laundry"],
  },
  {
    $id: "prop-17",
    name: "Artistic Loft Studio",
    address: "111 Artist Alley, Creative Quarter",
    price: 1800,
    rating: 4.5,
    type: "Studios",
    image: getPropertyImage(1),
    description: "Inspiring loft studio in the heart of the arts district.",
    bedrooms: 0,
    bathrooms: 1,
    area: 900,
    facilities: ["Wifi", "Laundry"],
  },
  {
    $id: "prop-18",
    name: "Grand Villa Estate",
    address: "222 Grand Estate Road, Luxury Hills",
    price: 12000,
    rating: 5.0,
    type: "Villa",
    image: getPropertyImage(2),
    description: "Magnificent villa estate with private grounds and pool.",
    bedrooms: 6,
    bathrooms: 5,
    area: 6000,
    facilities: [
      "Wifi",
      "Gym",
      "Swimming pool",
      "Car Parking",
      "Pet Center",
      "Cutlery",
      "Sports Center",
    ],
  },
  {
    $id: "prop-19",
    name: "Modern Duplex Apartment",
    address: "333 Modern Avenue, Contemporary District",
    price: 3600,
    rating: 4.6,
    type: "Duplexes",
    image: getPropertyImage(3),
    description: "Stylish duplex apartment with modern design.",
    bedrooms: 2,
    bathrooms: 2,
    area: 1700,
    facilities: ["Wifi", "Gym", "Car Parking"],
  },
  {
    $id: "prop-20",
    name: "Affordable Family House",
    address: "444 Affordable Street, Budget District",
    price: 1800,
    rating: 3.9,
    type: "House",
    image: getPropertyImage(4),
    description: "Affordable family home in a quiet neighborhood.",
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    facilities: ["Wifi", "Car Parking"],
  },
];
